# NumPY

In [50]:
import numpy as np

In [51]:
print(np.__version__)

1.26.4


# Creating NumPy Arrays( 1D, 2D, and 3D)

In [5]:
import numpy as np

#creating a 1D array from a list
array_1d = np.array([1,2,3,4,5])
print("1D array:", array_1d)

1D array: [1 2 3 4 5]


In [6]:
#creating a 2D array (Matrix) from a nested list
array_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("2D array:\n", array_2d)

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#creating a 3D array (tensor) from a nested list
array_3d = np.array([[[1,2], [3,4]],[[5,6],[7,8]]])
print("3D array:\n", array_3d)

3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Array Attributes (shape, size, dtype)

shape: the dimentions of the array ie 1d, 2d, 3d


size: the total number of elements in the array


dtype: the data type of the elements in the array

In [8]:
print("shape:", array_2d.shape)
print("size:", array_2d.size)
print("data types:", array_2d.dtype)

shape: (3, 3)
size: 9
data types: int32


# Indexing and Slicing Arrays

In [9]:
#Creating a 1D array from a list
array_1d = np.array([1,2,3,4,5])
print("1D array:", array_1d)

#indexng a 1d array
print(array_1d[0])

print (array_1d[-1])

#slicing a 1D array
print(array_1d[1:4])

1D array: [1 2 3 4 5]
1
5
[2 3 4]


In [11]:
array_2d =np.array([[1,2,3], [4,5,6], [7,8,9]])
print("2D array:\n", array_2d)

#Indexing a 2d array
print(array_2d[1, 2])

#slicing a 2D array
print(array_2d[0:2, 1:])

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[[2 3]
 [5 6]]


# Reshaping and Flattening Arrays

In [12]:
#Reshape a 1d array to a 2D array
reshaped_array = array_1d.reshape(5, 1)
print("reshaped array:\n", reshaped_array)

reshaped array:
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [13]:
#Flattening a 2D array
flattened_array = array_2d.flatten()
print("flattened array:", flattened_array)

#Alternatively, use the ravel function
flattened_array = np.ravel(array_2d)
print("Flattened array using ravel:", flattened_array)

flattened array: [1 2 3 4 5 6 7 8 9]
Flattened array using ravel: [1 2 3 4 5 6 7 8 9]


# Array Operations

In [14]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

addition = a + b
print("addition:", addition)

subtraction = a - b
print("subtraction:", subtraction)

multiplication = a * b
print("multiplication:", multiplication)

division = a / b
print("division:", division)

addition: [5 7 9]
subtraction: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]


# Broadcasting

Allows you to perform arithmatic operations on arrays of different shapes, as long as they are compartible.

Broadcasting rules:
    If an array have a different number of dimensions, the smaller shape is padded with one on its left side
    if the shape of the arrays does not match in any diemension, numpy tries to streatch the dimensions with size 1 to match the other array size in the dimension
    if any dimension size still do not match, a broadcasting error is raised

In [16]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
d = np.array([1,0,1])

broadcasted_sum = c + d
print("Broadcast sum: \n", broadcasted_sum)

Broadcast sum: 
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [18]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
d = np.array([1,0,1])

broadcasted_product = c * d
print("Broadcast product: \n", broadcasted_product)

Broadcast product: 
 [[1 0 3]
 [4 0 6]
 [7 0 9]]


# Element_wise Operation

In [19]:
#square root
sqrt_array = np.sqrt(a)
print("Square root:", sqrt_array)

#Logarithm
log_array = np.log(a)
print("Natural algorithm:", log_array)

#Sine
sin_array = np.sin(a)
print("Sine:", sin_array)

#cosine
cos_array = np.cos(a)
print("cosine:", cos_array)

Square root: [1.         1.41421356 1.73205081]
Natural algorithm: [0.         0.69314718 1.09861229]
Sine: [0.84147098 0.90929743 0.14112001]
cosine: [ 0.54030231 -0.41614684 -0.9899925 ]


# Statistical Functions

In [20]:
import numpy as np
data = np.array([4,5,1,2,7,2,6,3,5,2])

In [21]:
#Mean
mean = np.mean(data)
print("Mean:", mean)

#Median
median = np.median(data)
print("median:", median)

Mean: 3.7
median: 3.5


In [28]:
#Mode
from scipy import stats

mode = stats.mode(data)
print("Mode:", mode.mode, "Frequency:", mode.count)


Mode: 2 Frequency: 3


In [29]:
#Variance
variance = np.var(data)
print("Variance:", variance)

Variance: 3.6100000000000003


In [30]:
#Stansard Deviation
std_dev = np.std(data)
print("Statand Deviation:", std_dev)

Statand Deviation: 1.9000000000000001


# Random Number Generation

 Uniform distribution

In [34]:
#Generate a single random number between 0 and 1
uniform_random = np.random.rand()
print("uniform random number:", uniform_random)

#Generating an array of random numbers from a uniform distribution
uniform_array = np.random.rand(5)
print("uniform random array:", uniform_array)

#Generate random numbers between a custom range
custom_uniform_array = np.random.uniform(5, 10, size=5)
print("custom uniform random array:", custom_uniform_array)

uniform random number: 0.9086266588043288
uniform random array: [0.83495843 0.79412829 0.94017403 0.73606334 0.35388836]
custom uniform random array: [8.75511548 8.27126325 6.21585013 9.15309522 5.04056415]


    Normal Distribution
    - To generate random numbers from a normal distribution, use np.random.randn for a standard normal distribution(mean 0, standard deviation 1), or np.random.normal for a custom distribution

In [36]:
#Generate a single random number from a standard normal distribution
normal_random = np.random.randn()
print("Normal random number:", normal_random)

#Generate an array of random numbers from a standard normal distribution
normal_array = np.random.randn(5)
print("Normal random array:", normal_array)

#Generate a random number from a custom normal distribution(mean 5, standard deviation 2)
custom_normal_array = np.random.normal(5, 2, size=5)
print("Custom normal random array:", custom_normal_array)

Normal random number: -0.06146237668654141
Normal random array: [-0.09243329 -1.20297926  0.52792877  0.53006405  0.19285245]
Custom normal random array: [0.42338776 5.23635824 3.87399092 7.53608748 6.43077983]


Setting a random seed

In [37]:
np.random.seed(42)

random_array = np.random.rand(5)
print("Random array with seed 42:", random_array)

Random array with seed 42: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


# Numpy Assignment and solutions

In [41]:
#Calculate the mean, median and standard deviation of the students' heights
height = np.array([160,155,172,165,180,158,175,163,171,168])

mean = np.mean(height)
print("Mean:", mean)

median = np.median(height)
print("Median:", median)

std_dev = np.std(height)
print("Std Deviation:", std_dev)

Mean: 166.7
Median: 166.5
Std Deviation: 7.5372408744845085


In [45]:
#Create a new array with the heights normalized, i.e., each height value should be transformed to have a mean of 0 and a standard deviation of 1.
normalized_heights = (height - mean) / std_dev
print("Normalized Heights:", normalized_heights)

Normalized Heights: [-0.88891945 -1.55229217  0.70317509 -0.22554673  1.76457144 -1.15426854
  1.10119872 -0.49089581  0.57050054  0.17247691]


In [47]:
#Determine the tallest and the shortest student
tallest = np.argmax(height)
shortest = np.argmin(height)
print("tallest student:", tallest)
print("Shortest Student:", shortest)

tallest student: 4
Shortest Student: 1


In [48]:
#Calculate the difference between the shortest and the tallest
H_dif = height[tallest] - height[shortest]
print(f"Height Difference: {H_dif}")

Height Difference: 25


In [49]:
#Ramndomly select 5 heights from the dataset without replacement
np.random.seed(42)
random_selection = np.random.choice(height, size=5,replace=False)
print("Randomly selected heights:", random_selection)

Randomly selected heights: [171 155 158 160 163]
